"""
核心模块
包含配置、类型定义等核心功能
"""
from .config import (
    RUNNINGHUB_APP_TASK_KEY,
    RUNNINGHUB_DIRECT_API_KEY,
    RUNNINGHUB_BASE_URL,
    USE_MOCK_SERVICE,
    MAX_CONCURRENT_APP_TASKS,
    MAX_CONCURRENT_API_TASKS,
    API_TASK_TYPES,
    POLL_INTERVAL,
    API_POLL_INTERVAL,
    UPLOAD_DIR,
    DB_FILE_PATH,
    MAX_UPLOAD_SIZE,
    ALLOWED_IMAGE_TYPES,
    get_api_key,
    validate_config
)

from .platforms import (
    PLATFORMS_CONFIG,
    get_platform_config,
    get_enabled_platforms,
    get_platforms_for_task_type,
    get_platform_api_key,
    get_platform_endpoint,
    TASK_TYPE_CONFIG,
    get_task_type_config,
    get_all_task_types
)

from .models import (
    MODELS_CONFIG,
    get_model_config,
    get_enabled_models,
    get_model_capabilities,
    get_task_types_for_model,
    is_task_type_supported,
    get_capability_config,
    get_all_model_ids
)

__all__ = [
    'RUNNINGHUB_APP_TASK_KEY',
    'RUNNINGHUB_DIRECT_API_KEY',
    'RUNNINGHUB_BASE_URL',
    'USE_MOCK_SERVICE',
    'MAX_CONCURRENT_APP_TASKS',
    'MAX_CONCURRENT_API_TASKS',
    'API_TASK_TYPES',
    'POLL_INTERVAL',
    'API_POLL_INTERVAL',
    'UPLOAD_DIR',
    'DB_FILE_PATH',
    'MAX_UPLOAD_SIZE',
    'ALLOWED_IMAGE_TYPES',
    'get_api_key',
    'validate_config',
    'PLATFORMS_CONFIG',
    'get_platform_config',
    'get_enabled_platforms',
    'get_platforms_for_task_type',
    'get_platform_api_key',
    'get_platform_endpoint',
    'TASK_TYPE_CONFIG',
    'get_task_type_config',
    'get_all_task_types',
    'MODELS_CONFIG',
    'get_model_config',
    'get_enabled_models',
    'get_model_capabilities',
    'get_task_types_for_model',
    'is_task_type_supported',
    'get_capability_config',
    'get_all_model_ids'
]
